CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS airbnb_listing;

CREATE TABLE airbnb_listing(
    id bigint NOT NULL,
    listing_url text NOT NULL,
    scrape_id DECIMAL(14, 0) NOT NULL,
    last_scraped timestamp without time zone NOT NULL,
    name text,
    summary text,
    space text,
    description text,
    experiences_offered varchar(4) NOT NULL,
    neighborhood_overview text,
    notes text,
    transit text,
    access text,
    interaction text,
    house_rules text,
    thumbnail_url varchar,
    medium_url varchar,
    picture_url text NOT NULL,
    xl_picture_url text,
    host_id integer NOT NULL,
    host_url text NOT NULL,
    host_name text NOT NULL,
    host_since timestamp without time zone NOT NULL,
    host_location text,
    host_about text,
    host_response_time varchar(18) NOT NULL,
    host_response_rate varchar(4) NOT NULL,
    host_acceptance_rate text NOT NULL,
    host_is_superhost boolean NOT NULL,
    host_thumbnail_url text NOT NULL,
    host_picture_url text NOT NULL,
    host_neighbourhood text,
    host_listings_count integer NOT NULL,
    host_total_listings_count integer NOT NULL,
    host_verifications text NOT NULL,
    host_has_profile_pic boolean NOT NULL,
    host_identity_verified boolean NOT NULL,
    street text NOT NULL,
    neighbourhood text NOT NULL,
    neighbourhood_cleansed text NOT NULL,
    neighbourhood_group_cleansed text,
    city text,
    state text,
    zipcode varchar(5),
    market text,
    smart_location text NOT NULL,
    country_code varchar(2) NOT NULL,
    country text NOT NULL,
    latitude DECIMAL(7, 5) NOT NULL,
    longitude DECIMAL(8, 5) NOT NULL,
    is_location_exact boolean NOT NULL,
    property_type varchar(18) NOT NULL,
    room_type varchar(15) NOT NULL,
    accommodates integer NOT NULL,
    bathrooms DECIMAL(3, 1),
    bedrooms integer,
    beds integer,
    bed_type text NOT NULL,
    amenities text NOT NULL,
    square_feet varchar(4),
    price varchar(10) NOT NULL,
    weekly_price varchar(10),
    monthly_price varchar(11),
    security_deposit varchar(10),
    cleaning_fee varchar(8),
    guests_included integer NOT NULL,
    extra_people text NOT NULL,
    minimum_nights integer NOT NULL,
    maximum_nights integer NOT NULL,
    minimum_minimum_nights integer NOT NULL,
    maximum_minimum_nights integer NOT NULL,
    minimum_maximum_nights integer NOT NULL,
    maximum_maximum_nights integer NOT NULL,
    minimum_nights_avg_ntm DECIMAL(11, 2) NOT NULL,
    maximum_nights_avg_ntm DECIMAL(11, 2) NOT NULL,
    calendar_updated text NOT NULL,
    has_availability boolean NOT NULL,
    availability_30 integer NOT NULL,
    availability_60 integer NOT NULL,
    availability_90 integer NOT NULL,
    availability_365 integer NOT NULL,
    calendar_last_scraped timestamp without time zone NOT NULL,
    number_of_reviews integer NOT NULL,
    number_of_reviews_ltm integer NOT NULL,
    first_review timestamp without time zone,
    last_review timestamp without time zone,
    review_scores_rating integer,
    review_scores_accuracy integer,
    review_scores_cleanliness integer,
    review_scores_checkin integer,
    review_scores_communication integer,
    review_scores_location integer,
    review_scores_value integer,
    requires_license boolean NOT NULL,
    license text,
    jurisdiction_names text,
    instant_bookable boolean NOT NULL,
    is_business_travel_ready boolean NOT NULL,
    cancellation_policy text NOT NULL,
    require_guest_profile_picture boolean NOT NULL,
    require_guest_phone_verification boolean NOT NULL,
    calculated_host_listings_count integer NOT NULL,
    calculated_host_listings_count_entire_homes integer NOT NULL,
    calculated_host_listings_count_private_rooms integer NOT NULL,
    calculated_host_listings_count_shared_rooms integer NOT NULL,
    reviews_per_month DECIMAL(4, 2),
    description_embedding vector(1536),
    PRIMARY KEY (id)
);

